Feat: Updated Tokens
SickDesignSystem/sds pull request #54
Opened 2023-09-25 07:49 UTC by reichst1SICKAG

# Pull Request

## 📖 Description

### 🎫 Issues

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

## ✅ Checklist

### General

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have made sure to follow the projects coding and contribution guides.

### Component

- [ ] I have created a new component.
- [ ] I have added changes to an already existing component.
- [ ] I have written integration tests (or have adjusted already existing ones).
- [ ] I have validated that there are no accessibility errors.
- [ ] I have created or updated any stories affected by my changes.
- [ ] I have used design tokens instead of fix css values

2023-09-25 11:50 UTC, schilchSICKAG requested changes
I have found a couple of problems with the new tokens. We should talk about those before merging.

2023-09-25 11:50 UTC, schilchSICKAG commented on packages/design-tokens/tokens/semantic/typography-default.json
I get multiple warnings because of this file. The issue may be caused because typo default and small are using the same definitions, but just one definition can be loaded at the same time. This leaves the question how we want to mitigate this. Should we skip semantic tokens completely, use typo-default or typo-small? Also, as far as I can tell, each token should have a `value` prop that has the final value included, but for those files we have a structure similiar to the one below:

```javascript
        "xs": {
          "value": {
            "fontFamily": "{font.family.default}",
            "fontWeight": "{font.weight.bold}",
            "lineHeight": "{font.lineheight.140}",
            "fontSize": "{font.size.size-200}"
          },
          "type": "typography"
        },
```

Suggestion:

Should use the following structure:

```javascript
        "xs": {
            "fontFamily": {
              "value": "{font.family.default}"
            },
            "fontWeight": {
              "value": "{font.weight.bold}"
            }
```

2023-09-25 11:50 UTC, schilchSICKAG commented on packages/design-tokens/tokens/core/color.json
Colors are nested one level too deep, resulting in final names like `--sds-color-neutral-neutral-900` or `--sds-color-primary-primary-400`. Suggestion: Change this:

```javascript
  "color": {
    "primary": {
      "primary-3": {
        "value": "#E5F6FF",
        "type": "color",
        "description": "Primary-3"
      },
```

to

```javascript
  "color": {
    "primary": {
      "3": {
        "value": "#E5F6FF",
        "type": "color",
        "description": "Primary-3"
      },
```

to make names less verbose.

2023-09-26 08:58 UTC, reichst1SICKAG commented on packages/design-tokens/tokens/core/color.json
yeah, the naming looks like duplicates which is not ;)
the first 'primary' is the group and the name ist 'primary-3' because just '3' is not a good name

Maybe it works better when we change the group name from primary to 'main' or 'brand' like `--sds-color-brand-primary-3`
This works quite good, if you look at the status colors.

2023-09-27 09:27 UTC, reichst1SICKAG commented on packages/design-tokens/tokens/semantic/typography-default.json
Another idea is to remove those few semantic tokens for now, and insert them when we need them. Altough it would be good to have them in Figma to use them for documentation text or other stuff.

I only inserted them to test the semantic structure in Figma and to define the heading/body text definitions somewhere as tokens.

2023-09-28 06:33 UTC, schilchSICKAG commented on packages/design-tokens/tokens/semantic/typography-default.json
I have removed the semantic tokens from the current bundle for the time being.

2023-09-28 06:34 UTC, schilchSICKAG approved these changes

2023-09-28 06:35 UTC, schilchSICKAG commented
Adjusted documentation to make it work again, removed semantic tokens from building for the time being.

2023-09-28 06:37 UTC, merged